### ISSUE TITLE
Error loading .svg file

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb2#10]
When I try and load an svg file I get the following error:

TypeError: Cannot read property 'position' of undefined
(http://openhardwarecoza.github.io/LaserWeb2/js/fileprep.js on line 72)

**Comment by ghost** [comment]
Convert to path first (:

And the svg should only contain paths,  nothing else

**Comment by funinthefalls** [comment]
That was the issue, I had one element that was not a path.

**Comment by ghost** [comment]
Would be a good idea to code some error handling in to alert user to the
fact (;

I'll see what i can do

**Comment by cojarbi** [comment]
Could something like this be added  maybe? 

https://github.com/wout/svg.topath.js

AY

**Comment by ghost** [comment]
That particular one,  sadly no,  since its for svg.js.   We use snap.svg (;
-  try hunting down a plugin for snap.svg

**Comment by cojarbi** [comment]
Maybe this https://github.com/jwdavistx/svg-path-finder
