### ISSUE TITLE
Trouble with svg files

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb2#14]
I get this error when opening svg files
TypeError: fileParentGroup is undefined
(http://openhardwarecoza.github.io/LaserWeb2/js/fileprep.js on line 72)

**Comment by ghost** [comment]
Please post the troublesome SVG file?
The new library needs SVG containing ONLY paths

**Comment by funinthefalls** [comment]
That would be the issue then, I had one little raster in it.

**Comment by ghost** [comment]
I'll promise to make it better, soon, at the moment the machine connectivity needs some more urgent attention (:

**Comment by funinthefalls** [comment]
No problem :)
