### ISSUE TITLE
Device Names and Windows

### ISSUE THREAD

**Issue by ghost** [openhardwarecoza/LaserWeb2#23]
Joe ( @prcdslnc13 ) reported that LaserWeb2 on Windows fails to connect to the device.  We need to get rid of the /dev/  (;

**Comment by ghost** [comment]
Give it a try now?  I went through the trouble to install Windows 10 (bye bye ubuntu - I'm now tired of your nuisances) to test this out (; works for me on Grbl

**Comment by funinthefalls** [comment]
Welcome to the world of Windows Peter.

**Comment by ghost** [comment]
@prcdslnc13 can i  close this now?  Works for me on windows with grbl
