### ISSUE TITLE
Alternative CAM operations: CNC, Mill, Dragknife

### ISSUE THREAD

**Issue by ghost** [openhardwarecoza/LaserWeb2#24]
@rafffel  reminded me that we want LaserWeb to eventually be a full cam solution:

https://github.com/openhardwarecoza/LaserWeb/issues /118 relates.

But basically, the framework is there
1.  We need someone to help work on adding the drag knife rotate moves
2.  We can do mill/pocket operations using the clipper offset paths code already in there. 

js/threegcode.js is your friend (:

**Comment by rafffel** [comment]
i have started new branch for dragknife and multitool prupose

**Comment by ghost** [comment]
@rafffel - just peeking in, how's your work going on this? (:
