### ISSUE TITLE
SVG:  Nested Groups - snap.svg needs flattened groups

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb2#29]
I get this when loading an svg or inkscake svg
Same file in LW1 works ok.

[LW2 copy.svg.txt](https://github.com/openhardwarecoza/LaserWeb2/files/225226/LW2.copy.svg.txt)
[LW2P copy.svg.txt](https://github.com/openhardwarecoza/LaserWeb2/files/225227/LW2P.copy.svg.txt)

TypeError: Cannot read property 'position' of undefined
(http://openhardwarecoza.github.io/LaserWeb2/js/fileprep.js on line 72)

**Comment by ghost** [comment]
Only paths.  Convert everything to paths,  and remove non path objects.
Thats becoming a faq (;

This is a cnc after all (;

**Comment by cojarbi** [comment]
I'm going to hit the computer with a hammer. Inkscape says they all are paths with N amount of nodes

**Comment by Cinezaster** [comment]
File is fine, contains only paths.
The paths are wrapped by two `<g> <g>...paths </g> </g>` removed one and then it works.

**Comment by cojarbi** [comment]
@Cinezaster good to know that I'm not mad. How can we prevent that from becoming a problem or why is Inkscape doing that?

**Comment by ellisgl** [comment]
It looks like a known issue: http://wiki.inkscape.org/wiki/index.php/Save_Cleaned_SVG

**Comment by Cinezaster** [comment]
I only know how you can prevent this in illustrator. 
We should find a fix for this in the code, i'm already looking at it. 
Problem is that different groups can have different translations which causes problems (in laserweb).
Save_Cleaned_SVG is the best option for now.

**Comment by cojarbi** [comment]
How do you prevent it with illustrator? It's great if you can fix it on the code, that way you prevent futures cases like mine or and thus giving a great experience to the user

**Comment by ellisgl** [comment]
In inkscape - you can save as a plain SVG (second item on the drop list when saving as). See if that helps. I've done a couple tests, but couldn't get the double g's.

**Comment by ghost** [comment]
From what I understand, we can run the svg through flatten.js (https://gist.github.com/timo22345/9413158) to fix the transform groups... Tricky one

**Comment by Cinezaster** [comment]
In illustrator select a group and then degroup. Do this for all groups!

**Comment by ghost** [comment]
Ok i tried out flatten.js but still have a `<g>` inside a `<g>`

**Comment by ghost** [comment]
We now get this...

![lw2-post](https://cloud.githubusercontent.com/assets/7695323/14649467/65b5dcd0-0667-11e6-8d82-e7590bd742cc.PNG)

**Comment by openhardwarecoza** [comment]
Okay definately breaks here: on line 124  https://github.com/openhardwarecoza/LaserWeb2/blob/gh-pages/js/svg-render.js#L124

(Uncommenting breaks it again):

`//path = path.transform(path.parent().transform().global);`

path.parent:?  Which parent. It has no parent (;

![path](https://cloud.githubusercontent.com/assets/7695323/14649645/47186a94-0668-11e6-856a-06e33524eda3.PNG)

**Comment by ghost** [comment]
Further digging:  Paths that work have G as a parent. Paths that dont,  have a M as a parent
... causes   path = path.transform(path.parent().transform().global); on line 124 of svg-renderer.js to freak out

**Comment by openhardwarecoza** [comment]
I can't recall, I have this in https://github.com/openhardwarecoza/LaserWeb/blob/master/i/svg/js/SVGRenderer.js laserweb1. don't think it was actually used...

**Comment by ghost** [comment]
I'm seriously considering moving back to the SVGReader library we used in LaserWeb1 - snap.svg has some funnies :(

**Comment by ghost** [comment]
Right, svgreader.js in place - closing this issue for now.

I'll be adding some enhancements for SVG soon again (per color power/speed etc) but for now what I have in is a direct replacement for what we had with snap.svg
