### ISSUE TITLE
X Y movement arrows suggestions change

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb2#30]
Is it possible to change the layout of this buttons to reflect X and Y in a cross pattern instead of side by side?

**Comment by ghost** [comment]
@cojarbi :  Like this?

![new jog](https://cloud.githubusercontent.com/assets/7695323/14820564/7b6f2d78-0bc7-11e6-8d30-3e649d9457a6.PNG)

**Comment by cojarbi** [comment]
I think it's the best layout and makes it easier for everybody but will take a lot of screen realstate. Maybe something smaller like Chilli

**Comment by cojarbi** [comment]
Ooooo I just saw you changed the whole thing.

**Comment by ghost** [comment]
![shaded](https://cloud.githubusercontent.com/assets/7695323/14821774/4c8986fc-0bcc-11e6-9b34-cf44c228d4d7.PNG)

Yip whole new feel (:

Just because i've been offline a lot, doesnt mean I've been idle (;

Go play on the live version (; and let me know what you think

Real estate is the biggest goal now + touch friendlyness: Those fabcreators come with a 1024x768 touch tft (;

**Comment by cojarbi** [comment]
I'm sure even in your sleep you are making changes, upgrades, etc.

**Comment by cojarbi** [comment]
Kind of complicated the Móvil experience https://imgur.com/vDcHWbF

**Comment by ghost** [comment]
True,  but the minimum resolution i'll cater for is a horizontal 7"
tablet.   Phones are just not the ideal platform

**Comment by cojarbi** [comment]
Maybe phone just as a remote control. Much like the plugging for octoprint

**Comment by cojarbi** [comment]
Can you make it so if press a button it opens the widget and if i press it again it closes it?

**Comment by ghost** [comment]
Phone as dongle:  i have some exciting (cheap) hardware on its way to
OpenBuilds to solve that one.  (;

Close widget: clicking View closes all widgets.   Coding it to close is a
possibility but i want the top toolbar to be more like a 'wizard'  guiding
users through opening,  setting up,  sending.  (not quite like i want it
just yet)

**Comment by ghost** [comment]
Gonna make the widgets draggable so you can see preview without them
obscuring your view

**Comment by ghost** [comment]
New UI in progress....
