### ISSUE TITLE
Offset between raster image preview and calculated raster

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb2#31]
Zoom in to the raster and youll notice that the calculated path has slight offset to the left. 
Is this:
affecting the actual location of the raster
its a bug from the image preview
Its part of the code originally intended by @nathanielstenzel 
Else?
<img width="1877" alt="screen shot 2016-04-22 at 7 49 36 am" src="https://cloud.githubusercontent.com/assets/16444438/14741954/4a64bf06-085f-11e6-9df1-df4c5c1b7a24.png">

**Comment by ghost** [comment]
Part  of that original 'raster to the point'  instead of 'from the point'
-  i just need shift the png/bmp/jpg over by spotSize

**Comment by cojarbi** [comment]
Ok, understood. Look at this one. Its all over the place. Does the zoom/resolution slider affect the output if the image if not scaled properly to the dot size?
<img width="570" alt="screen shot 2016-04-22 at 8 01 35 am" src="https://cloud.githubusercontent.com/assets/16444438/14742257/c5e7dffe-0860-11e6-9d50-00c418086dba.png">

**Comment by ghost** [comment]
There are probably some rounding errors too.  I recall the bounding box
(gray size preview)  in LW1 did the same when you drag the mouse to set
spotsize but not if you used keyboard.  Noted that this does need some
enhancement though...  Busy week at work sadly :(

**Comment by cojarbi** [comment]
Yeah Work. Why do we need that.

**Comment by ghost** [comment]
(;  thats a sadly true conundrum (;

**Comment by nathanielstenzel** [comment]
Something that may help is if you can get it to render the path with a dot size. In other words, any line from point A to point B should end in circles around A and B and be as thick as the dot diameter. I had tried to get it to render like that before and failed.

**Comment by nathanielstenzel** [comment]
That last image does look odd. Make sure you use parenthesis when doing math and structure it right when rendering. It kind of looks like someone got some sort of rectangle based math going on for the rendering and might have it structured wrong. That is just a guess though. If doing scaling of xmin and xmax, you should be doing scaled_xmin = (xmin- dotsize/2)×scale and scaled_xmax = (xmax+dotsize/2)×scale for the x bounds of the line, for example. Well, I hope that helps.

**Comment by ghost** [comment]
The preview is scaled as actual image dimensions × spotsize.    But the
gcode is actual size × spotsize + 1px left padding + 1/2 px right.   The
jquery ui slider also introduces error:  the preview is sized as a callback
from the slider.  But the gcode is sized by reading the slider val later.
Sometimes when you drag too fast the callback doesnt fire.  When you nidge
the slider with the keyboard it does.

What really needs to happen:   paperjs can resize a raster to any number of
dots we need.    Right now we let the user fuss with spotsize as zoom. But
actually spotsize is a constant on your machine -  we should adjust the
number of dots to change zoom.

**Comment by ghost** [comment]
Give it a try now @cojarbi

**Comment by ghost** [comment]
![linesup](https://cloud.githubusercontent.com/assets/7695323/14887057/53767e82-0d54-11e6-8cbd-6e0ca27b7213.PNG)

**Comment by ghost** [comment]
![test](https://cloud.githubusercontent.com/assets/7695323/14887290/6ee9727c-0d55-11e6-8591-3e3f8e59c4e2.PNG)
another test

**Comment by cojarbi** [comment]
I'm getting the same results without scaling. When scaling it does not line up
![20160428_090436](https://cloud.githubusercontent.com/assets/16444438/14888554/9185cd60-0d20-11e6-8a11-c4dc72ab70be.jpg)
![20160428_090621](https://cloud.githubusercontent.com/assets/16444438/14888576/a1c52414-0d20-11e6-9efa-e904d9e9e804.jpg)

**Comment by ghost** [comment]
Using mouse or keyboard on slider?  Mouse has inaccuracy

**Comment by MetalMusings** [comment]
Hi all,
I looked at this and know what happens.
The "slide:" event in $("#spotsizeslider").slider() (raster.js) seems not to be generated or caught for the final position. So the image on the screen and the slider value show one thing, when the raster button is pressed the last position of the slider is retrieved and used in g-code generation. Therefor the difference.

I duplicated the "slide: " function into a "change:" function (around line 85 in raster.js) and at least the images come out the same size. It is not the ideal solution though that anyone that tries it will find. But it shows were the problem is. 

Hopefully someone can take this info and find a real solution.

**Comment by ghost** [comment]
Yeah, i'l try escalate the bug upstream to jqueryui - but its an acceptable fix. Send pull when you get a chance?

**Comment by ghost** [comment]
nevermind, figured out what you meant:  Fire the "change" event from http://api.jqueryui.com/slider/

**Comment by ghost** [comment]
Thanks @HakanBastedt !

Size matches perfectly

![spot on](https://cloud.githubusercontent.com/assets/7695323/15453245/c9e84a92-200e-11e6-9e74-b4a29951c61f.PNG)

**Comment by cojarbi** [comment]
Awesome @hakannastedt

AY
