### ISSUE TITLE
Raster image not working only getting one single line

### ISSUE THREAD

**Issue by Cinezaster** [openhardwarecoza/LaserWeb2#32]
I'm trying to do an engraving with the file / raster generator. I'll see in the other issues that the feature is working, but I actually never managed to generate gcode from a raster image. All I get is this:
![schermafbeelding 2016-04-29 om 10 30 21](https://cloud.githubusercontent.com/assets/188269/14911727/8eda2552-0df7-11e6-8ccb-dcd2548e395c.png)
One straight move.
What do I do wrong?

**Comment by ghost** [comment]
Weird one.  Post the file please?

**Comment by ghost** [comment]
Test file:

![openbuilds_blackbox_logo](https://cloud.githubusercontent.com/assets/7695323/14912523/2aaba802-0dfd-11e6-8118-ee4c02122ac1.jpg)

Result

![tested](https://cloud.githubusercontent.com/assets/7695323/14912552/56b99f6c-0dfd-11e6-9fbf-e0aefcdf9ed0.PNG)

**Comment by Cinezaster** [comment]
This was the file.
![hackaday](https://cloud.githubusercontent.com/assets/188269/14914780/a4dfcbc0-0e0d-11e6-8632-6aa32ab38afc.png)

I used your test file.
![schermafbeelding 2016-04-29 om 13 23 31](https://cloud.githubusercontent.com/assets/188269/14914912/be5b45ec-0e0e-11e6-8c47-531c7c5be447.png)
![schermafbeelding 2016-04-29 om 13 23 24](https://cloud.githubusercontent.com/assets/188269/14914914/c1bc97d6-0e0e-11e6-8433-ca8252aaa6ea.png)

**Comment by ghost** [comment]
![jolly](https://cloud.githubusercontent.com/assets/7695323/14915551/4689380c-0e14-11e6-8d1d-9c326094cbc1.PNG)

Ok so we eliminated file...

**Comment by ghost** [comment]
Aha, managed to replicate it:

If you forget to set a PWM max value in settings... it does this.  Need to add some defensive code to warn user to not to forget machine setup (;

![pwms](https://cloud.githubusercontent.com/assets/7695323/14915677/12bd8d4c-0e15-11e6-908b-8d07b5a1b306.PNG)

**Comment by Cinezaster** [comment]
Thx. I don't have my laser connected, that is why I didn't pay attention to the setting.
