### ISSUE TITLE
Show file name

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb2#33]
Can we get LW to show the file name in use

**Comment by ghost** [comment]
(: Any tips on where?   As in where in the gui. I cant seem to find a spot that feels right

**Comment by cojarbi** [comment]
As you open files on the top left, thats where if feel it's natural, so it could also benefit the Google Drive load you can place the name just bellow the "open from drive"

**Comment by ghost** [comment]
![filename](https://cloud.githubusercontent.com/assets/7695323/15545480/ba72f8ba-229c-11e6-93c4-919085623a75.PNG)

Figured out that I can add more things onto the 3D viewer... Might be crazy, but I kind of like the idea of using the canvas for this sort of "info" like filenames, job time estimates, etc

**Comment by cojarbi** [comment]
I did no suggest there because though was not possible. 

Look very good.  Migth also suggest on the top left of the canvas as a "tab"  as all GUI this days use that in one way or the other

AY

**Comment by ghost** [comment]
Ahh!   You just cracked ny biggest gui worry!  How do display multiple
layers and set each's cam job!!!!  By adding tabs!  Why didnt i think of
that!   You just gave me the gift i've been looking for week!  As you add
jobs,  i add tabs to the top.   Allows user to switch between files and
tweak each 'layer',   when we run final job,  we iterate through each
tab.   Each tab can have its own cam,  own gcode textarea,  etc.   One
final tab shows everything stacked.  F%ck this is going to look awesome.

**Comment by cojarbi** [comment]
Exelent. Full speed ahead. I did no suggest anything there bacause of the many times you told me that area was untouchable. 

Defenetly tabs is the best way to go.  Clean,  simple and today everybody are use to them. 

AY

**Comment by ghost** [comment]
Thanks again.  Tabs take so little space,  and from a flow perspective,
its just perfect.  Makes sense.  I like UIs that make sense

**Comment by cojarbi** [comment]
Regarding the name dont know if your seen but opening gdrive files does not show the file name

**Comment by ghost** [comment]
I know,  totally different set if functions to the normal button

**Comment by ghost** [comment]
Closed,  since filenames will be the tabs too
