### ISSUE TITLE
Loading same file wont show update

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb2#34]
If i load a file but then change the original and load again without refreshing the browser it wont update itself. This can cause problem while connected

**Comment by ghost** [comment]
Unable to replicate this issue...

Without refresh I can open new files...

**Comment by cojarbi** [comment]
Ok so open an svg, then in Inkscape open that svg and change something, open that same svg in LW. It will no refresh the file. Like if it's name allready in the memory

**Comment by ghost** [comment]
Ahh yes that makes sense.  I watch for a change in the filename on the
input block to kickoff a load...  Ok let me see what i can do.

**Comment by ghost** [comment]
Right i dont think this one broke it like last time (;
