### ISSUE TITLE
Load settings from controller into laserweb

### ISSUE THREAD

**Issue by Cinezaster** [openhardwarecoza/LaserWeb2#35]
In grbl you can receive the size of your cnc by asking the settings. The grbl object already contains the size of the cnc after you send `$$` command, by storing all the data into it's memory.

It could or should set the size of the cnc in laserweb. 

Since I'm gonna start implementing the TinyG & TinyG2 object, we should think about a flow to retrieve data from our controllers to have a validation layer in laser web that generates better gcode that does not try to go faster or is not going to hit the limits of the machine.

**Comment by ghost** [comment]
Agreed.  Good idea.

**Comment by ghost** [comment]
Conversely we can push the bed size to the machine when changing it in the
gui too (;

**Comment by Cinezaster** [comment]
OfCourse, that would be the whole point. But then we need our controller communication layers.
