### ISSUE TITLE
Adding Kerf option to STL Slice and Rotate STL

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb2#40]
Sliced results edges are on top of each other. 

<img width="1879" alt="screen shot 2016-05-04 at 8 56 48 pm" src="https://cloud.githubusercontent.com/assets/16444438/15034450/7cba370c-123b-11e6-8967-436dbe9263b6.png">

**Comment by ghost** [comment]
kerf: added 3mm...

rotate: We're working on that in meshes.js and chilipeppr-3dprint - will bring back here once it actually works.
