### ISSUE TITLE
Touchpad Enable/Disable executes only after browser refresh 

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb2#41]
After saving the selection nothing happens. Only after refresh

**Comment by ghost** [comment]
Yes, and it states it clearly on the settings tab

![screenshot from 2016-05-05 15-07-54](https://cloud.githubusercontent.com/assets/7695323/15044154/3dd9b10a-12d3-11e6-87c7-dfd692c9d436.png)

**Comment by ghost** [comment]
Those are all things that affect a LOT of vars, so best to refresh:
Camera, bed size, Numpads, Gcode Values, etc....
