### ISSUE TITLE
Google drive files

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb2#42]
Selecting SVG produces the following " ReferenceError: drawSVG is not defined (http://openhardwarecoza.github.io/LaserWeb2/js/googlesignin.js on line 123)"

DXF load without issues

BMP and jpg don't show at all

Maybe show a pop-up like touchpad to select file im afraid that a long list will move the whole left side of the interface down.

Did you apply a maximum? I just added a folder inside the drive and reduced the files showen minus one but does not show the folder
<img width="366" alt="screen shot 2016-05-04 at 9 09 10 pm" src="https://cloud.githubusercontent.com/assets/16444438/15034668/8d31006e-123d-11e6-90ea-2b56b01cc611.png">

**Comment by ghost** [comment]
It still has to move to a tab of its own

**Comment by yuusuf-sallahuddin** [comment]
<img width="1440" alt="laserweb 05 open from drive issue" src="https://cloud.githubusercontent.com/assets/19544785/15503390/ee2b8014-21fc-11e6-8eb3-20030b2624aa.png">
Issue here for me with the G Drive integration whereby it seems to list only some of the files in my G Drive. I've got a tonne of folders in my G Drive & I'm not seeing any way to navigate the folder structure.

**Comment by ghost** [comment]
I'll add folders later.  For now i am filtering only files we support
(dxf,  svg,  bitmaps)

**Comment by ghost** [comment]
Folders integrated. Just updating here for someone looking later perhaps...
