### ISSUE TITLE
Home control does not work with Marlin

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb2#46]
All the jog buttons work, however I cannot make it home using the home button. Also the abort job button only works about 50% of the time for me.

**Comment by ghost** [comment]
Home:.. Did you remember to configure the settings,. Gcode,  Homing
Sequence?

Abort: clears the spjs queue,  but there's still a buffer on the controller
that meeds to finish first

**Comment by funinthefalls** [comment]
Will save the settings again and give it a try. Hopefully that is all that was wrong. On a different subject, I am getting very strange results from the raster function. I will post the gcode it creates along with the original bitmap. Other that that I am really liking the workflow in LaserWeb 2. It is turning into a great piece of software Peter, you deserve a great deal of praise for your efforts.

**Comment by ghost** [comment]
Yip send over files (;

**Comment by ghost** [comment]
If you see weird burn patterns - that's why i hate marlin.  Doesnt have
power as function of acceleration: so acceleration and deceleration has
darker burns :(

**Comment by funinthefalls** [comment]
Here are the files.

![bday](https://cloud.githubusercontent.com/assets/3101946/15238617/198d41ce-18a8-11e6-8861-7d69f8d54373.png)
[bday.gcode.txt](https://github.com/openhardwarecoza/LaserWeb2/files/262583/bday.gcode.txt)

**Comment by funinthefalls** [comment]
TYhe home issue was due to not saving the home codes properly....dumb mistake on my part.

**Comment by ghost** [comment]
Transparent BG PNGs confuse the heck out of paper.js when I ask it to report the "gray level" of the pixel.   Merge down and export as flat preferable with a white background

**Comment by funinthefalls** [comment]
OK, will give it a try.

**Comment by funinthefalls** [comment]
That fixed it,thanks! Closing the issue
