### ISSUE TITLE
Marlin and greyscale artifacts

### ISSUE THREAD

**Issue by mayhem2408** [openhardwarecoza/LaserWeb2#47]
I think my issue is specifically with Marlin, but I am seeing artifacts in some grayscale burns. It is not due to acceleration as I have tried constant feed speeds where no acceleration is needed. I think the issue might be with the 16 command look ahead limit in marlin. If there are to many pixel intensity changes to close together, the laser stops moving for a split second as marlin catches up. The reason I think this is the issue is because I do not see a problem with the calibration pattern which does not have a large number of intensity changes in very quick succession. Has anyone else seen this?

**Comment by ghost** [comment]
if you checkout the other branches https://github.com/TurnkeyTyranny/buildlog-lasercutter-marlin/network  then TurnkeyTyranny is starting to look old.   Investigate the other branches thats further ahead for potential fixes (view their commit logs) 

Also,  make sure you do the larger serial buffer upload as proposed by @nextime on the laserweb1  issue for the same.  

At the end of the day,  this is a firmware issue,  tracking down what exactly,  i cant help much
