### ISSUE TITLE
Keeps previous gcode settings

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb2#48]
So i open a file, generated the code the open another file and the previous gcode is still there. 

More over when you go to convert to generate a new code it keeps showing and accumulating the previous one. Is this by design? It does execute the correc one.
<img width="1859" alt="screen shot 2016-05-14 at 8 42 19 pm" src="https://cloud.githubusercontent.com/assets/16444438/15271539/0b25761a-1a15-11e6-9501-d9a2fc48a6a2.png">
<img width="1861" alt="screen shot 2016-05-14 at 8 44 24 pm" src="https://cloud.githubusercontent.com/assets/16444438/15271538/0b1ccab0-1a15-11e6-8b0c-00ba15fafa4b.png">

**Comment by ghost** [comment]
Is this still an issue?

**Comment by cojarbi** [comment]
It does. Just tested svg. No dxf at hand

**Comment by ghost** [comment]
Okay so #59 relates... Need to fixup threeCleanUp function...

**Comment by ghost** [comment]
Okay testing OK on my side, waiting for your confirmation

**Comment by cojarbi** [comment]
So it does clear the previous image but still leaves the previous setup in the convert section
<img width="1849" alt="screen shot 2016-05-25 at 1 38 54 pm" src="https://cloud.githubusercontent.com/assets/16444438/15552019/3ab63ee8-227e-11e6-8da3-3f3d10429c30.png">
t tab
