### ISSUE TITLE
Add baud rate 250000 to index.html

### ISSUE THREAD

**Issue by frazierjason** [openhardwarecoza/LaserWeb2#50]
Consider adding 250000 baud as an available option.  It's a common baud rate, and seems to be more stable than 230400 for some users on USB serial UART clones.

**Comment by ghost** [comment]
(: 10 mins from opening issue, to considered, implemented and live (;

There you go (;

**Comment by frazierjason** [comment]
awesome, thanks!

-------- Original message --------
