### ISSUE TITLE
Opening bitmaps - returns error

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb2#54]
I keep getting this error when trying to open bitmaps:

TypeError: evt.target.files[0] is undefined (http://openhardwarecoza.github.io/LaserWeb2/js/main.js on line 391)

I have tried about 30 different bitmaps, always with the same result.

**Comment by ghost** [comment]
Fixed in https://github.com/openhardwarecoza/LaserWeb2/commit/aed6293830f8e9960796bd18d0e27b582a7886b3
