### ISSUE TITLE
Controller support/wiring status and default use-case

### ISSUE THREAD

**Issue by SloMusti** [openhardwarecoza/LaserWeb2#56]
I am in the process of testing LaserWeb and am choosing the controller firmware had hardware, however there do not seem to be any clear directions yet. 

Based on tickets support for Marlin/Smoothieware/Grbl is under development and thus would be a good idea to nicely display what id the default, most operational path. 

Happy to prepare this, just ping your replies which firmware should be the best choice.

**Comment by ghost** [comment]
Smoothieware is definately the 'default'.
Second best is Grbl
Third is marlin
TinyG status is 'coming soon'

Smoothieware is the only one the does laser power as a variable function of
acceleration,  makes for much better cuts and engraves.

In all cases gcode generation is working perfectly fine.  Serial sending is
the WIP.
