### ISSUE TITLE
Running LaserWeb2 locally ( on Rasspberry Pi)

### ISSUE THREAD

**Issue by dilon007** [openhardwarecoza/LaserWeb2#58]
I have a problem .
How to run the LaserWeb2 locally on Rasspberry Pi.(like LaserWeb2)
Which server(app or software) need to installed.
Can you help me?

**Comment by ghost** [comment]
Please try not to.  Its developing very rapidly,  staying online means
staying up to date.  I'll release instructions when its finished (not while
we are changing things daily)
(if you cant figure out how to run it yourself,  it means you'll likely
also not be able to stay up to date)
