### ISSUE TITLE
Raster startgcode is not defined

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb2#6]
Error after pressing prepare raster

ReferenceError: startgcode is not defined
(http://openhardwarecoza.github.io/LaserWeb2/js/laserraster.js line 77)

Added G92 in LW options thinking i had to. Same result

**Comment by ghost** [comment]
Fixed!

**Comment by cojarbi** [comment]
Getting this now 
TypeError: Cannot read property 'updateMatrixWorld' of undefined

(http://openhardwarecoza.github.io/LaserWeb2/lib/threejs/three.min.js line 87)

**Comment by ghost** [comment]
cosmetic, mthat just updates any objects on scene...
