### ISSUE TITLE
Gcode generation optimization (G0)

### ISSUE THREAD

**Issue by 666dsa666** [openhardwarecoza/LaserWeb2#60]
I will gladly wait a few more seconds for the gcode to be generated if I can get X seconds back with an optimized Gcode (for batches with more than one run)

http://xyzbots.com/gcode-optimizer/

There is a few command line toolq on github too.

**Comment by ghost** [comment]
Sadly, I can't (wont) ever use any code from Andrew (xyzbots) -refer to the fights in thread https://github.com/openhardwarecoza/LaserWeb/issues/27#issuecomment-167587329 and also some offline ones. Some days he helps, rest of the time he expects you to stroke his ego, most of the time you dont know where you stand with him 

I am opposed to outright "optimise the G0 moves" too - we are working on a much more advanced cutting algorith to ensure inside parts are cut first.
