### ISSUE TITLE
Opening files in upper left quadrant - does not work with bitmaps

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb2#62]
When I open an SVG file, it correctly places it in the upper left quadrant, but bitmaps always open on lower left quadrant.

**Comment by ghost** [comment]
This is on the roadmap as part of the "layers" thing - the group will obey the quadrant, but the raster and cut files inside the group needs to be manually positionable...

**Comment by funinthefalls** [comment]
OK, thanks

**Comment by ghost** [comment]
Pushed a fix for this, please test.

**Comment by ghost** [comment]
Forgot to account offset, added as well

**Comment by funinthefalls** [comment]
Works good. Thank you once again.
