### ISSUE TITLE
Config file check broken

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb2#69]
LaserWeb is still looking for spjsip on startup. Creates error "Checking : spjsip : NOT SET undefined" which gives:
! Incomplete Config
Please complete configuration

**Comment by ghost** [comment]
Fixed in https://github.com/openhardwarecoza/LaserWeb2/commit/f01caed228dcf1622cf954b7982dd6f13b4d5dcd (used wrong issue number in commit name)
