### ISSUE TITLE
COM port, Buffer, Machine controls and DRO are misssing

### ISSUE THREAD

**Issue by athulsnair** [openhardwarecoza/LaserWeb2#71]
COM port, Buffer, Machine controls and DRO are misssing in LaserWeb2.

Also Chrome  crashes most times after generating raster gcodes. tried in two laptops
![12](https://cloud.githubusercontent.com/assets/16574115/15884667/b2a80fe8-2d6f-11e6-8de1-c71f2b56f6ed.jpg)

**Comment by ghost** [comment]
See #52  - we are jumping ship on the Serialportjsonserver concept - see github.com/openhardwarecoza/LaserWeb3 for its replacement
