### ISSUE TITLE
Connect in menu bar missing

### ISSUE THREAD

**Issue by SloMusti** [openhardwarecoza/LaserWeb2#72]
Tested LaserWeb2 about 10 days ago just fine, now however there appear to be only Open and full-screen buttons in top bar when on Chrome+Win7, worked fine on the same machine before. Something broke I guess. New version looks awesome already, but would be nice to use this one meanwhile.

**Comment by cojarbi** [comment]
@slomusti LW2 is just a CAM now. All efforts are on LW3 which is running fine for smoothie.

**Comment by SloMusti** [comment]
Are there any live versions we could use with Grbl as we had people running machines that way.

**Comment by cojarbi** [comment]
Maybe Look for an older version in github and run it locally.

**Comment by cojarbi** [comment]
On windows cmd root do

git clone https://github.com/openhardwarecoza/LaserWeb2.git
go into laserweb2 directory
run " npm install "
run http-server to execute it

beside this you still need to run SPJS locally

**Comment by SloMusti** [comment]
Made a for to my github and have it running there: https://github.com/IRNAS/LaserWeb2 for use until replaced by new version. Making the change of features clear in https://github.com/openhardwarecoza/LaserWeb2/pull/73 request.

This issue can be closed from my perspective.

**Comment by cojarbi** [comment]
Good, thanks
