### ISSUE TITLE
Tool tips = feature enhancement (Implemented)

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb2#9]
Found this on the web:
http://projects.nickstakenburg.com/tipped/documentation

If you implement this in the overall design, I can go through and add context sensitive tool tips where they make sense, makes for a much more user friendly app in my opinion.

**Comment by ghost** [comment]
We already have tooltips support in jqueryui (http://api.jqueryui.com/tooltip/) which is anyway there for the sliders and a few other elements already. So wont need t use Nick's 

I've pushed a commit to initialise tooltips in main.js for the entire DOM

That means ANY element that you think needs a tooltip just has to get a title="tooltip here!"

For example, say we have the file open button?

`<span class="btn btn-default btn-file"><i class="fa fa-folder-open fa-fw"></i>Open<input id="file" type="file" accept=".png,.jpg,.jpeg,.bmp,.gcode,.g,.svg,.dxf,.stl" /></span>`

Lets add a toolip to the btn

`<span class="btn btn-default btn-file" title="Open a file"><i class="fa fa-folder-open fa-fw"></i>Open<input id="file" type="file" accept=".png,.jpg,.jpeg,.bmp,.gcode,.g,.svg,.dxf,.stl" /></span>`

See https://github.com/openhardwarecoza/LaserWeb2/commit/80ada0d42c6713af251d859821835f8726a2d973 for the example (:

You can add **title="something"** to any thing you think needs a tooltip (in its most simple form.  With jqueryui we can have fancy in/out effects too. but in default it looks good enough)

**Comment by funinthefalls** [comment]
Thanks Peter, I will start adding them where I think they will help. Didn't realize that jqueryui  had the ability for tool tips. Learn something new everyday working with you. Slowly my coding skills are coming back.
